const HANDLE_INPUT = 0
const FETCH_COMPLETE = 1
const SUBMIT_COMPLETE = 2
const HANDLE_EDIT = 3
const SET_LOADING = 5
const RESET_FORM = 6

export {FETCH_COMPLETE,HANDLE_EDIT,HANDLE_INPUT,RESET_FORM,SET_LOADING,SUBMIT_COMPLETE}